---
Gemfile:
  optional:
    ':development':
      - gem: 'nokogiri'
        version: '~>1.8.1'
        platforms: 'ruby'
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  test_script:
    - 'bundle exec rspec spec/unit -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
