---
Gemfile:
  optional:
    ':development':
      - gem: 'nokogiri'
        version: '~>1.5.10'
        platforms: 'ruby'
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.3.0
      RUBY_VER: 193
  test_script:
    - 'bundle exec rspec spec/unit -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
