---
Rakefile:
  unmanaged: true
Gemfile:
  optional:
    ':system_tests':
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  test_script:
    - 'bundle exec rspec spec/unit -fd -b'
.travis.yml:
  extras:
    - rvm: 2.1.9
      script: bundle exec rake rubocop
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
